### ISSUE TITLE
Image Sequence Publishing

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#112]
### Goal

Automatically put a rendered or otherwise generated image sequence into the appropriate folder within a project and trigger any post-processes, such as Quicktime and thumbnail generation.

### Implementation

Once a render is complete, it ends up in the users working directory where it may then be published, initially via the command-line.

```bash
$ mb.bat
$ hulk film
$ 1000
$ cd render\marcus\maya\images\my_image_sequence
$ publish
```

The Pyblish GUI appears and takes the user through publishing the image sequence like any other asset.

**Comment by mottosso** [comment]
Suggested hierarchy from #104.

```bash
project\f02_prod\renders\{shot}\{renderLayer}\{sceneVersion}\{sceneName}.####.ext
# e.g. project\f02_prod\renders\sh010\background\v035\myScene_v012.####.ext
```

@Stonegrund, what are your thoughts on something like this?

```bash
project/f02_prod/film/{shot}/publish/{version}/{renderLayer}/{subset}.####.ext
# e.g. project/f02_prod/film/sh010/publish/v001/background/background.####.ext
```

Differences are:

1. Renders are stored under the given asset, in this case `sh010`, similar to other assets.
2. Scene name and version are discarded and available as either metadata or `background.source`

**Comment by Stonegrund** [comment]
Sounds good. The important part for me is that the compers can access it and it is trackable from to its origin. That is why I use '%s' so the sequence has the same name as the render scene. Because it happends that we sometimes render just an additional pass and save the scene as new version or even a different scene name. All the render layers  and passes does not necessarily have the same version, but it is easy to backtrack from which renderscene it has been rendered from if we had to make a custom renderScene for a specific pass or layer.

That is why we also make the scene version to also have the same version a the renderScene version. So sometimes we wont have v001, but instead v004 because the last assembled and saved renderScene before we render is v004, and no v005 but v008. If it makes sense?  

But if we can store some metadata to track from which scene the rendered sequence has been rendered from, then I am all up for to make a folder/publishing path as you have suggested :) I am sure you have had the same thought :)

**Comment by mottosso** [comment]
That makes sense, thanks Emre.

What I'm aiming for is enabling others to render into the same shot, without necessarily working on the same file or understand the workflow or setup of another artist. Embedding the internals of a particular working file on disk has the nasty side-effect of not scaling very well to that kind of workflow.

For example, if artist A and artist B both worked on a shot, and called their scenes `my_render_v001.ma`.

By keeping that information separate, as metadata, any number of artists could contribute to the stream of versions coming out of a single render, and contribute renders that differ entirely from another, such as a beauty pass from Maya and a smoke pass from Houdini - using its internal rendering engine and workflow.

**Comment by Stonegrund** [comment]
Sound lots of unicorns and rainbows to me ear. Superb!!

**Comment by BigRoy** [comment]
Closing this.

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.

Note that a multitude of studio configs already have developed some sort of image sequence publishing, as a reference feel free to investigate:
- [colorbleed-config](https://github.com/Colorbleed/colorbleed-config)
- [reveries-config](https://github.com/davidlatwe/reveries-config)
- [pype-config](https://github.com/pypeclub/pype)
