### ISSUE TITLE
Docker for Example Projects

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#182]
### Goal

Simplify setup of pipeline for a first-time user.

### Motivation

Before the asset database, installation was (1) limited to Windows but (2) reduced to a single `git clone ...`. Since then, we now require new users to not only `git clone ...` but also install database software (currently MongoDB). The database is to be configured and have a user assigned to it, with optional permission management.

This greatly complicates the life of anyone interested in testing the pipeline out who doesn't already posses knowledge in database management.

### Implementation

Along with [mindbender/example](https://github.com/mindbender-studio/example) we'll distribute a database dump in the form of a dictionary that can be automatically uploaded into the supplied Docker image.

```bash
mindbender-example/
  projects/
    hulk/
      assets/
      film/
      database.json
```

That would enables us to reduce installation to installing Docker, and further enables us to provide management tools for it, such as automatically uploading the database into it.

We'll use Docker for more things down the line, such as hosting the file synchronisation solution and web-services, like project and task management, so this could be a good opportunity to introduce it.

**Comment by davidpower** [comment]
Hi, Marcus.
I made some change in the example project, hope this could make the first kick a little more smooth.

### Motivation
Since I prefer to actual connecting a server, I didn't install monogDB on my windows at first, so when I tried to import the example project *batman*, `avalon --import batman` told me that "mongoimport not found".

### Result
After reading the code and some google, I think I can replace those mongo-tools with `pymongo`, and I did.
I forked the example project and **here is what I [changed](https://github.com/davidpower/examples/commit/3078263d3f39ff69bbd4c5dc4236ebae3ecbe7e0)**.
If this is okay, I could make a PR.

Also, I made a VM with **virtualBox**. It's an Ubuntu server with MongoDB setup.
Can be download here.
[avalon-server](https://drive.google.com/open?id=0B3d79-0ZvZ_DRlFWUU0tUGtCaEE)

<details>
<summary>Here is the login screen</summary>

<br>

Can see the IP and user/pwd in there.

<br>

![](https://i.imgur.com/5Y6b6IC.png)

</details>

**Comment by mottosso** [comment]
Wuuuw, that's looking sweeeet! :D

**Comment by mottosso** [comment]
Could you walk me through how you envision a new user installing Avalon with this for the first time?

**Comment by davidpower** [comment]
Sure! But not envision, this was what I have been doing for now and how I introduce to my colleagues.

Kind of trade-off between mongoDB setup and virtual stuff setup.
This is currently on Windows, but should easy to do the same on other platform.


1. Download VirtualBox and Extension-pack [here](https://www.virtualbox.org/wiki/Downloads), and install them.
1. Download Python 3.6 64-bit [here](https://www.python.org/downloads/windows/) and install.
	1. Install `Python 3.6 64-bit` to `C:\Python36_64`
1. pip Install `virtualenv`.
	1. Add `C:\Python36_64\Scripts` in to system environment variable `PATH`.
	1. Open CMD, run `$ pip install virtualenv`
1. download `__kick__` package [here](https://drive.google.com/drive/folders/0B3d79-0ZvZ_DOThkWWVkd3lDeFE?usp=sharing), put them into a place where you want to try Avalon.
	> There are 3 files in the package, `python3.dll`, `setenv.bat` and `build_avalon_env.bat`
	> `python3.dll` is for this fix, and the batch is for auto build an avalon virtual environment later.
1. Right-click and execute `build_avalon_env.bat`, and it will start download all the git and do the setup.
1. Turn on VM, note down the IP and database info, and leave it there.
1. In CMD, cd to the `avalon_env` folder just created, and activate virtualenv.
	```
	$ cd /d path\to\avalon_env
	$ Scripts\activate
	```
1. Edit `AVALON_MONGO` URI in side the `setenv.bat`, and run it.
	```
	$ setenv
	```
1. Jump in to Avalon.
	```
	$ avalon --import batman
	$ avalon
	```

**Comment by davidpower** [comment]
Docker could be easier, but my studio are still on windows 7, so I might try this Docker thing at home.

**Comment by davidpower** [comment]
Just playing around with Docker. Add everything avalon needs in to a [dockerfile](https://gist.github.com/davidpower/9998dee5eba05f6dca9db57717273497#file-dockerfile-avalon), can interact with another mongo container ( `avalon --import batman` ) ,  but stock at showing Launcher GUI from docker on windows.I tried CygwinX, Xming still no succeeded. Linux should be easier. My brain is jammed. 😢

If Launcher can have a CLI like **be**, should easily ship in with Docker, than the only thing needs to install is Docker. But not sure

**Comment by mottosso** [comment]
Yeah, that's the problem with Docker. If you do manage to start the Launcher GUI from Docker, you'll still struggle to launch actual software like Maya in the host OS.

Docker works great for running non-graphical processes, like MongoDB. You could run `mayapy` and things from it as well, but at the end of the day the artists will need Maya running graphically and locally.

You *can* get Launcher to run within Docker, but what you'll need is either (1) graphics drivers that exactly match those on your host OS, which won't work under Windows either way as it's running under VirtualBox or Hyper-V or (2) Mesa drivers to run in software OpenGL mode. And as you experienced, you'll need a host X-server running; I'm using VcXsrv personally, but either of those you listed should work as well.

And *if* you manage to somehow get Launcher running from Docker, or if you run something like **be**, then assuming the only barrier is launching Maya and friends on the host OS, it's possible we could run a simple Python server in addition to Docker to take commands for launching Maya.

For example, the Launcher running in Docker could say..

```python
from xmlrpc.client import ServerProxy
proxy = ServerProxy("http://ip-to-host-OS")
proxy.launch("c:/program files/autodesk/maya2015/bin/maya.exe")
```

But that's assuming a lot..

Suffice to say, bundling up a pipeline is no easy task.

**Comment by davidlatwe** [comment]
Not sure this has been through before or not, but I found that MongoDB is providing free database service (250MB storage), setting that up is quite simple, maybe a good option for who doesn't or can't use Docker to build mongodb.
https://www.mongodb.com/cloud/atlas?jmp=nav

**Comment by mottosso** [comment]
I did investigate that, there are a few more free services too. But I couldn't get the process any shorter; the user needs to sign up on some service and then you have a potential firewall to consider and help the user through. :(

**Comment by davidlatwe** [comment]
What do you think about using [TinyDB](https://github.com/msiemens/tinydb) with [TinyMongo](https://github.com/schapman1974/tinymongo) for demo ?

Could set a environ var `USE_TINYDB`, and tweak `io.py` from
```python
imoprt pymongo
self._mongo_client = pymongo.MongoClient(
        Session["AVALON_MONGO"], serverSelectionTimeoutMS=timeout)
```
to something like
```python
import database
self._mongo_client = database.db_client()
```
And depend on the demo mode or not, return `pymongo.MongoClient` or `tinymongo.TinyMongoClient` from that module `database.py`.

Although before handing over `TinyMongoClient` to `io.py`, it needs to be wrapped with some missing equivalent `pymongo` methods used in `io.py`, like `distinct()`, `drop()`, `save()`, or `find_one()` dosen't take arg `projection`, and the `_id` is a string instead of `ObjectId`,..., but those should be easy to take care of.

**Comment by davidlatwe** [comment]
Or, no, just found out that `tinymongo` query with operator is buggy, need fix.

**Comment by mottosso** [comment]
Good thinking @davidlatwe, I also went down that road with TinyDB, but again no luck. :( My problem there was, as you also found, the interface differed too much.

**Comment by tokejepsen** [comment]
Could possibly close this, because of https://github.com/getavalon/docker ?

**Comment by mottosso** [comment]
Yes, I think we've got a winner.
