### ISSUE TITLE
Instance Creator - Locking the family name

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#278]
_Note: This issue corresponds or partial corresponds with issues #194 / #246 / #269_

# Discussion
In our studio one of the artists rewrote the entire subset name to `"sign"` in two different tasks, modeling and lookdev. After publishing the artist could not find her published files anymore due to the lookdev files being stored in the same folder under `v002`. What happened was what @mkolar actually described.

```
Example result in publish folder:
prop_sign/
--sign/
----/v001/sign.ma (model)
----/v002/sign.ma (lookdev)
```

# Our solution
To counter this from happening we want to lock the `family` name in the `subset`. Everything being made from that point on will always lead with the family name, e.g.: "lookWet".

We also want to remove `name` attribute from the Creator class and focusing solely on the `family` attribute. This is possible by using the `string.rsplit` which is already in use in the current Instance Creator.

# Conflicts
* Backwards compatibility
    In the case of the current logic (1) vs new logic (2):
    1. `label = (plugin.name or plugin.family.lower().rsplit(".", 1)[-1] + "Default")`
    2. `label = "Default"` , this will result in `{family}Default`
    We might not be able to create instances which need to have very specific names such as `RenderGlobals`.

* publishing variants
    When locking the family we will no be able to implement the logic proposed in #269 to publish subsets/variants nicely even though this also result in non-backwards compatible paths or being forced migrate those already published.

Thoughts are welcome!

**Comment by mottosso** [comment]
> In our studio one of the artists rewrote the entire subset name to "sign" in two different tasks,

This is not a design flaw, but misuse.

Here, "sign" isn't the name of a subset but the name of an asset. A subset is part of an asset, like a `model` or a `rig`. Here, a `sign` is part of a `sign`, which doesn't make any sense, hence the problem.

I'm not opposed changing things, but we shouldn't do it to accommodate for misuse. We should instead prevent misuse from happening, and then talk about design changes. For example by not enabling the user to type the name of a subset, but to choose it. If the choice is going to be the family, then why not remove the textfield altogether? Let it be just the family.

In this case, what does `sign` as a subset actually refer to? What was the *intent*?

The scenario is:

1. The user picks "lookdev" from the list of available families
2. The subset name field is automatically filled in, e.g. `lookdevDefault`
3. The user then changes the name to `sign`

I think what you're after is to disable editing of the `lookdev` part of the name and leave `Default` in the subset name field. Making `Default` more of a qualifier or description of the full subset name. And that's allright, I see no problem with that. But I think it's important to highlight that there it wouldn't be a change to accommodate for this particular form of misuse, but because we've chatted about it before and it makes sense at a general level. If that makes sense!

Do comment on the *intent* however, I think that could help paint a clearer picture of what actually went wrong here and potentially something we could also address, separately.

**Comment by BigRoy** [comment]
> I think what you're after is to disable editing of the lookdev part of the name and leave Default in the subset name field. Making Default more of a qualifier or description of the full subset name. And that's allright, I see no problem with that. But I think it's important to highlight that there it wouldn't be a change to accommodate for this particular form of misuse, but because we've chatted about it before and it makes sense at a general level. If that makes sense!

Just to be sure, yes. But the idea behind the argumentation was more that in that hindsight it made no sense for both of the exactly named subsets be of a different family. As such only the `lookDefault` and `modelDefault` made sense (if they are required to have a prefix of the family, otherwise both the `look` and `model` can end up being `default`, which might currently clash?

As such, locking the family with the subset. Full on yes, like: https://github.com/getavalon/core/issues/246

Regarding this implementation I'd want to note two things:
- https://github.com/getavalon/core/issues/269 In this particular issue the subset name would then never end up being `default`, but in `model` be `modelDefault`
- https://github.com/mindbender-studio/config/blob/master/polly/plugins/maya/create/mindbender_renderglobals.py This one won't work exactly like it is mentioned there anymore, as the prefix I believe would become `renderglobals` and not `renderGlobals`. As such, that particular creator might not end up being backwards compatible, since the resulting subset will become different, e.g. `renderglobalsDefault`

**Comment by mottosso** [comment]
>  This one won't work exactly like it is mentioned there anymore, as the prefix I believe would become renderglobals and not renderGlobals.

That's the `id` attribute, not the name of the node. It's independent from family or node name, it's the equivalent of `avalon.instance` to discover instances in the scene. Should be unaffected by this change.

**Comment by BigRoy** [comment]
>  Should be unaffected by this change.

Are you sure?

Previously the `plugin.name` was used as default name for the subset: https://github.com/getavalon/core/blob/master/avalon/tools/creator/app.py#L116

Which in your case is `renderGlobals`. With this issue implementing a required prefix of the family in the subset's name this means it will become: `renderglobalsDefault` because the family is `mindbender.renderglobals`. As such, you could never match the subset name `renderGlobals` anymore.

**Comment by BigRoy** [comment]
With #283 this now forces (through the instance creator only; not in the core api) that publishes now always have their family name prefixed in the subset, for example:

- modelDefault (family: "colorbleed.model", name: "default")
- rigDefault (family: "colorbleed.rig", name: "default")
- lookRed (family: "colorbleed.look", name: "red")

@mkolar I remember you had some specific questions regarding having "family" stored in the subset. What do you think of this?

**Comment by mkolar** [comment]
It pretty much solves the issues I've had with the system in regards to families and subsets. 

The question that remains is whether the subsets have their family stored in them as well as data, on top of having it in the name. My point is that I should be able to look  up a subset and query what family it is a be certain that all it's versions have the same family

**Comment by BigRoy** [comment]
> The question that remains is whether the subsets have their family stored in them as well as data, on top of having it in the name. My point is that I should be able to look  up a subset and query what family it is a be certain that all it's versions have the same family 

Totally agree; it should be stored in the subset. :) That particular issue I believe is: https://github.com/getavalon/core/issues/246

**Comment by mottosso** [comment]
This has been implemented in https://github.com/getavalon/core/pull/283?

**Comment by aardschok** [comment]
Yes, the commit contains that implementation
