### ISSUE TITLE
Improve Application environment management system

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#311]
### Discussion

To me it feels like the `.toml` files for Applications just don't give us the granularity of control that we're looking for. Specifically into managing the App's environment, the issues I'm having are:

- I can't inherit from another `.toml` environment or "stack" environments. For example, I might want my Maya for project X to have: `global,maya_2018,mtoa2018_xx,yeti2018_yy` which would then combine a set of dependencies, similar to [this](https://github.com/tokejepsen/ftrack-hooks/tree/master/dynamic_environment).
- I can't ensure an order of the environment variables, say I want to set `PIPELINE_ROOT` and then have all the rest of the variables using `{PIPELINE_ROOT}/xx/yy` then I can't do so from within that single `.toml` file, because it's a dictionary and I can't ensure `PIPELINE_ROOT` was set prior to the other one.
- I can't "append" my environment variable to an existing one if it originally doesn't exist instead of just allowing it to merge with an empty value - similar to `%PYTHONPATH%;path/to/x;path/to/y;`

We might want to look into a slightly more full blown system or drop the importance of the `.toml` files. With Actions being implemented with #306 the `.toml` importance might already be reduced a lot, even for the launcher. Because I could instead register my own actions instead of letting the launcher parse them from the `.toml` - for example I could use an action that uses a much more elaborate library like [Ecosystem](https://github.com/PeregrineLabs/Ecosystem) or [rez](https://github.com/nerdvegas/rez/wiki).

#####  Reproduce the exact environment of an app

An also important use case to me is "reproducing the environment" on the farm for example. So that when a Deadline job kicks in, it reads this "environment dependencies", reproduces it and starts the render. So I'm imagining the app starts an has something like `APP_DEPENDENCIES` set to: `maya_2018,mtoa_2.0.1,yeti_2.1.0,golaem_5_2017` so that the slave can reproduce it (even cross-OS compatible).

#### References

- [Ecosystem](https://github.com/PeregrineLabs/Ecosystem)
- [Rez](https://github.com/nerdvegas/rez/wiki)
- [Dynamic environment hooks for ftrack (by Toke Jepsen & Milan Kolar)](https://github.com/tokejepsen/ftrack-hooks/tree/master/dynamic_environment)

**Comment by tokejepsen** [comment]
Please note that dynamic environment hook for ftrack, was developed with @mkolar (Milan).

**Comment by BigRoy** [comment]
> Please note that dynamic environment hook for ftrack, was developed with @mkolar (Milan).

Thanks, updated the original post.

**Comment by mottosso** [comment]
Thanks @BigRoy, good thoughts. As a general rule of thumb, I tend to think that the simplest thing to any problem is the most complex solution.

Another way of putting it is that the most difficult thing to do is finding the simplest solution to a complex problem, and I think this is one of them.

So, Just for completeness..

> I can't inherit from another .toml environment or "stack" environments.

Have you considered/tried stacking of executables? E.g.

- `maya.bat` sets global variables, for every project and version of Maya
- `maya_2015.bat` calls `maya.bat`, and sets things specific to 2015, but global to every project
- `arnold.bat` ...
- `arnold_2018.bat` ...

Then, per project, you have..

- `maya_projectX.bat` to launch Maya, calling things in the order you need
- `nuke_projectX.bat` to launch ...

> We might want to look into a slightly more full blown system or drop the importance of the .toml files. 

Before throwing out the baby with the bathwater, let's narrow the problem down a little. The problem seems to revolve around more granular control over environment variables.

At the moment, an executable is referenced in your `.toml`, where the executable can be a `.bat` file where you set and tweak variables to your liking. It would be possible to, say, include logic in that .bat file.

```bat
if "%SOME_CONDITION%" do %THIS%
```

Additionally, the `.bat` file may be something other than a `.bat` file, such as a Python script.

```python
import os
import subprocess

if os.environ["SOME_CONDITION"]:
  subprocess.Popen(...)
```

Hence your `.toml` file includes "triggers" or "switches" for what the executable is to do. This goes in hand with what executables normally do; like how Maya boots up differently given different environment variables, and may therefore be a non-surprising workflow.

With your executables are more capable, they could include things like a CLI.

```python
import os
import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--renderer")

args = parser.parse_args()
if args.renderer == "arnold":
  os.environ["SOME_VARIABLE"] = "SOME_VALUE"

subprocess.Popen(...)
```

Which you could use in your `.toml` (*and standalone*) as such.

```toml
...
arguments = [ "--renderer", "redshift" ]
```

Again, to me the important thing is getting the most functionality out of the least amount of features. Especially core, and important features surrounding environment management. This may not be enough, but should hopefully be some food for thought!

**Comment by mottosso** [comment]
> Hence your .toml file includes "triggers" or "switches" for what the executable is to do

To expand on this, what I mean is that the TOML could include variables for your executable, rather than the actual application directly. Like a layer inbetween.

```python
[environment]
USE_ARNOLD = True
DISABLE_VIEWPORT2 = True
LOCK_HOMEDIR = False
DO_X = Maybe
IS_AWESOME = Definitely
```

Your script then uses these to determine which variables to *actually* set in the application environment, which could cascade or stack in any way you like. Keeping your TOML file plain and readable, and complex logic in code where it belongs.

**Comment by BigRoy** [comment]
Ah, thanks - That makes total sense and seems to cover my needs. I made this [environment prototype package](https://github.com/BigRoy/env_prototype) to get an idea of my actual needs and did this test in the colorbleed configuration: https://github.com/BigRoy/colorbleed-config/commit/f24398fe11156363d47b0eb0b9ec2de5725de48b

I could now build up an application environment and run it from command-line like: 
```bat
python -m colorbleed.scripts.launch --tools "global;maya2018;yeti.2.2.4" --executable "maya"
```

Which of course could be defined in the `.toml` to also be triggered from the Avalon launcher.
It seems configurable enough looking at it that way.

**Comment by mottosso** [comment]
Ooo that's great! Always happy when simple solutions suffice. :)

There's a lot of room for innovation with this approach I think, and I think you've uncovered some already.

**Comment by BigRoy** [comment]
Yup, I'll close this issue for now. I believe the above discussion shows enough possibilities for others to explore. It can always be reopened if it seems to lack functionality down the line.
