### ISSUE TITLE
Discrepancy between fonts core and launcher

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#323]
__Issue__
When using the latest launcher we encounter icons which are not the icons we have set.
Example [here](https://user-images.githubusercontent.com/1860085/42269207-d595694e-7f7d-11e8-922d-c0ab7543c148.gif)

__Details__
When debugging the launcher we found that the icons used in the `tray icon context menu` were the issue because it loaded the `qtaweome` from Avalon core. We took a closer look and after opening the font files in both the `core` and the `launcher` we found that the version were not in sync.

_launcher:_ version 4.7.0
_core:_ version 4.4.1

We tried to match the versions for both repositories but even after matching it still showed discrepancies. Much less than before, that has to be said. It might be because of the type of font or the legend used to get the icons.

We have temporarily disabled the icons in the tray

**Comment by BigRoy** [comment]
Can you add a screenshot showing the difference between the icons we want and those that are wrong? I think with just the GIF now it's too confusing.

---

I think the issue is coming from the fact that both install the same font but a different version, thus it doesn't load correctly. @mottosso might know some techniques on how to ensure the fonts are loaded correctly and don't interfere with each other. Or maybe update Font-Awesome for both and ensure they are the *exact same version*. :)

**Comment by tokejepsen** [comment]
+1 for updating the versions

**Comment by aardschok** [comment]
This issue has been resolved, see merges
