### ISSUE TITLE
Nuke_workflow avalon.pipeline uninstall()

### ISSUE THREAD

**Issue by jezscha** [getavalon/core#354]
There is a discrepancy between running avalon.api.uninstall() from `maya` or `nuke`.

When I run `avalon.api.uninstall()` from Nuke it stops on 
```python
# Result: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\hubert\CODE\pype-setup\repos\avalon-core\avalon\pipeline.py", line 106, in uninstall
    registered_host().uninstall(config)
TypeError: uninstall() takes no arguments (1 given)
```

A solution is to add `except TypeError` on line 109 with `pass` 

I had fixed it in our fork and will be pushing it with the new PR `nuke_workflow` soon.

**Comment by tokejepsen** [comment]
Should it not be aligned with the Maya integration, so the uninstall takes the "config" argument?

**Comment by jezscha** [comment]
I had try and for a reason there is a difference between Maya an Nuke. Can
be uninstalled only if the TypeError exeption is added.

*Jakub Ježek*
Lead SW developer at Orbi.tools
+420 775 115 173

**Comment by tokejepsen** [comment]
It sounds odd that you would need a try/except in this method.
The error message only mentioned that it's not expecting an argument, so if you expect one in the Nuke integration, it still doesn't work?

**Comment by jezscha** [comment]
No it doesn't as it is shown in the log. It needs another exception for
Type as well. Or have you other suggestions?

*Jakub Ježek*
Lead SW developer at Orbi.tools
+420 775 115 173

**Comment by BigRoy** [comment]
The error posted in the first message in this issue should actually relate to what @tokejepsen is saying.

Avalon's api [`uninstall` function seems to call `uninstall` on the registered host with the `config` as argument](https://github.com/getavalon/core/blob/899b8896cda9d6c5426a21eee01a17a1e277e8fe/avalon/pipeline.py#L104). However the [nuke host doesn't implement it with a `config` argument in the function](https://github.com/getavalon/core/blob/899b8896cda9d6c5426a21eee01a17a1e277e8fe/avalon/nuke/pipeline.py#L29).

Changing that line to `def uninstall(config):` should fix the error mentioned at the top. If not, you should at least get a different error. Note that the Avalon core as is would already error out on `install()` because it doesn't have a merged nuke implementation yet - however both of the following PRs add the argument for `install()` yet forget to do so for `uninstall`: https://github.com/getavalon/core/pull/329 and https://github.com/getavalon/core/pull/344

**Comment by jezscha** [comment]
> Changing that line to def uninstall(config): should fix the error mentioned at the top. If not, you should at least get a different error. Note that the Avalon core as is would already error out on install() 

Thanks!

**Comment by tokejepsen** [comment]
Did that make the error go away?

**Comment by jezscha** [comment]
Yeah! Problem solved :) 

PS: I had miss-understand you.. language fog.. :)
