### ISSUE TITLE
Switch Subset - Better UI

### ISSUE THREAD

**Issue by mkolar** [getavalon/core#373]
We have multiple requests to make the dialog for switching a subset in the scene inventory somewhat more usable. 

Artists are having issues with selecting subsets from a huge list of all subsets on the project, which gets a bit unmanageable :). 

We'll try reusing widgets from other GUIs to make a small simplified loader for it. Functionality should be the same of course, but artist should be able to get to desired subset and representation quicker. 

Something like this maybe? so it's familiar...
![switch_asset_dialog](https://user-images.githubusercontent.com/3333008/52535603-bd6a3a80-2d50-11e9-9581-80c27ff70bc4.png)

**Comment by BigRoy** [comment]
The current switch UI can definitely use some improvement. If I correctly understand this is supposed to become the pop-up that shows whenever you click Switch Asset?

For sake of reference, here is a screenshot of the current switch UI:
![current_switch_ui](https://user-images.githubusercontent.com/2439881/52563559-0f1ecd80-2e02-11e9-95d9-69a2dea5ea0a.png)

---

The current switch UI might need some explanation as to why it's designed the way it is - albeit it is a quick first draft implementation.

You can choose to enter only one of the values and the others will remain the same. So if you just want to change to the same subset but from another asset you can decide to only enter the asset field, not needing to enter the "subset", "representation", etc. This is a feature that won't be possible with your design proposal, since you'll need to always be explicit about the full change.

Similarly you can currently select multiple loaded assets in the Scene Inventory (manager) and switch them all to another asset, by selecting all > switch assets > filling in only the asset field.

Also, instead of clicking to go through the full list I'd recommend starting to type so the autocomplete filters.

---

Proposal:

- Say we keep the same design/functionality but extend the UX to be more recognizable and increase selectability . The ideas would be:

1. Could a new design maybe work in such a way that when deciding on an asset (clicking on the dropdown for example) that it just shows the asset list (as in your example left hand side)?

2. Currently when selecting an asset (left hand side) in the switch view it doesn't filter the subset list. If we would implement that it would already reduce the amount of options that would be available.

3. Maybe a brief description or hint on the usage could be displayed as a label within the UI to aid the artist on how to use it and how it works with the empty entries.

**Comment by mkolar** [comment]
Aaaah. makes much more sense now. let me mull this over and I'll get back here. All the points you made are very good and I need to think a bit :).

**Comment by BigRoy** [comment]
Now that I think of it. :)

The UI could actually show the currently selected assets you are about to switch and the new entries that it resolves to - possibly making red for which it can't resolve (e.g. the same subset doesn't exist on the new asset). Then it's also directly clearer as to what the result will be after the switch.

Like a list at the bottom with green ones that are resolved and to what it gets resolved, and red for those that aren't being resolved. :)

Together with my previous notes that could be a pretty decent improvement.

**Comment by mkolar** [comment]
We have this implemented and in production. Will create PR soon to discuss the details. We've done practically exactly what @BigRoy suggested (minor tweaks) and it's usability is through the roof now.

**Comment by BigRoy** [comment]
Great, looking forward to it. Any sneak previews? :)

**Comment by BigRoy** [comment]
This has actually been much improved with: https://github.com/getavalon/core/pull/376 
However there is a new issue to discuss another level of improvement here: https://github.com/getavalon/core/issues/389

It seems different enough to close this.
