### ISSUE TITLE
'loader' and 'sceneinventory' don't use the current project when using `AVALON_DEBUG`

### ISSUE THREAD

**Issue by jasperges** [getavalon/core#460]
While working on the Blender integration I ran into something I thought was an issue with my code. When you have set `AVALON_DEBUG=1` the `loader` and `sceneinventory` use the first project from the database instead of the 'active' one.

See the relevant lines for the [loader](../blob/master/avalon/tools/loader/app.py#L417-L425) and the [sceneinventory](../blob/master/avalon/tools/sceneinventory/app.py#L931-L939).

To be honest I found this quite confusing. Is there a specific reason for this? Would it be okay to remove this?

**Comment by BigRoy** [comment]
Good question. I think the reason was to ease starting these tools in a quick test environment, but I agree that the behavior sounds confusing. I believe originally that code was written by @mottosso looking at the _BLAME_ reports on Github.

Does `AVALON_DEBUG` give any additional debugging output you actually need? I don't recall it actually becoming more verbose nor can I find much code related to `AVALON_DEBUG`. Is it useful either way? Aside of it being confusing.

Admittedly the `AVALON_DEBUG` as it currently is implemented feels more like `AVALON_DEMO` where it starts the tools in such a way that it "demos" the toolset. However I'd feel that should never run on a live database either way. Maybe if we need the behavior to persist so tools can easily initialize into a project without requiring to explicitly set it first this could be refactored to "demo" as opposed to "debug".

**Comment by jasperges** [comment]
After digging around a bit, it seems that `AVALON_DEBUG` is actually quite useless. I do use it a little bit in the Blender integration.

It would be nice to have a 'proper' debugging mode and probably also have a 'demo' mode. But that seems like quite a bit of work to get right and in my opinion doesn't have a very high priority.

I personally feel it would already be a good start to get rid of the 'confusing' behaviour in the `loader` and `sceneinventory`, but let's see what @mottosso has to say. :)

**Comment by jasperges** [comment]
Hi @mottosso, do you have time to have a quick glance and give your opinion?

**Comment by mottosso** [comment]
> When you have set AVALON_DEBUG=1 the loader and sceneinventory use the first project from the database instead of the 'active' one.

I'm equally stumped. :S Can't remember implementing this kind of behavior, would be happy to see it removed. Thanks for checking.
