### ISSUE TITLE
Single Loader Per Family

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#58]
### Goal

Simplify simplify simplify.

### Motivation

At the moment, loaders are identical to Pyblish plug-ins. Meaning each asset has a corresponding family and the family determines which of the registered loaders to run.

So far, there hasn't been a need for more than one loader, and in fact multiple loaders complicate logic and understanding. For example, should each loader create its own Container, and if so what does that mean? Loading an asset, like an animation cache, should ultimately end up in a single container, representative of the loaded animation. Currently, the animation could end up in multiple containers, what does that mean? What does each container represent?

### Implementation

One loader one family.

**Comment by mottosso** [comment]
This has a critical flaw. What should happen when loading an asset with more than one family, and a loader associated with both?

Need to rethink this.

**Comment by BigRoy** [comment]
This should be fixed since the #198 implementation. The loaders can be implemented per family and per representation and the user can pick which loader to use on which representation.

As such, at all times a single loader will be used. Furthermore it currently allows to implement multiple loaders for the same representation, and the user could pick one of them.
