### ISSUE TITLE
Lookdev Validator

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#98]
### Requirements

- [Hierarchy](#hierarchy)
- ?

#### Hierarchy

Each publish MUST contain the following hierarchy.

```bash
ROOT/
    ?/
    ?/
```

**Comment by mottosso** [comment]
@Stonegrund if you could have a think about and share your preferred hierarchy for lookdev publishes, then I could fill in the above and make sure it is done.

**Comment by Stonegrund** [comment]
This may differ from render engine to render engine but the base structure should be more or less the same.

```

Imported_asset_grp/      <---- This group is hidden in Outliner

ROOT/
     mesh_input/         <------This group is hidden in Outliner
                *mesh/

     mesh_output/
                **mesh/


historylookdevDefault_SET/
                         in_SET/
                               *mesh/
```

*is a clone of the original mesh (the connections to its original mesh had to be broken, so it can be exported separately and be able to connect to an alembic )
**is a clone of the clone mesh (keeps the connection to the clone it is cloned from, this it to make sure it behaves like the animated alembic. If alembic gets hidden for example, this visible clone also gets hidden)

If deformers are involved, such as `iDisplace` in this case, we had to have simple cubes to attach them to, so we could have an empty template scene and have the deformers still in the scene and with the settings we already set. Usually deformers needs geometry to be able to be kept in the scene. But this was unique to this project, but it is something to keep an eye on. 

Side thought: This procedure might be slightly altered after your implementation of issue #88 ?

**Comment by mottosso** [comment]
Thanks @stoneground, that's great.

> If deformers are involved, such as iDisplace in this case, we had to have simple cubes to attach them to

This shouldn't be necessary. The fact that you need this is either a bug or miscommunication. I'll take a closer look.

**Comment by Stonegrund** [comment]
Another request and question is:

Redshift attributes, object/material ID and Puzzle Matte

Redshift attributes: Under the drop-down menu in Maya for Redshift I will be using the `Object Properties` such as the `Mesh Parameters`. This are like modifications sets that also are on each geo shape, but instead of giving each mesh a subdivision I collect them in Redshift `Mesh Parameters`. There are other attributes as Matte and Visibility options that we will use as well. It would be nice if these also followed along with the lookdev. (again, this might be solved with `historyLookdevDefault_SET`,also if the mesh export is fixed.)

object/material ID and Puzzle Matte: Redshift uses so called `Puzzle Matte` to output RGB-masks. In the lookdev phase we already set the Material ID in the material shading group. It would be great to have the render scene to read the shading group and create puzzle matte AOV's. I don't think that will be the issue it self but to make sure that objects always have same color over every render. For example that candy01 is always green in the RGB matte. 

This is just another conversation starter for the render pipe.

**Comment by BigRoy** [comment]
Closing this. 

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.
